alias l=eza
alias ls=eza
alias la="eza -a"
alias lt="eza --tree"
alias ll="eza -l"
alias lla="eza -la"
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias md="mkdir -p"
alias rd="rmdir"
alias c="clear"
alias h="history 0"
alias path='print -l ${(s.:.)PATH}'
