alias pacin="doas pacman -S --color=always"
alias paccln="doas pacman -Sc --color=always"
alias pacsync="doas pacman -Sy --color=always"
alias pacsrch="doas pacman -Ss --color=always"
alias pacup="doas pacman -Syu --color=always"
alias pacrem="doas pacman -Rsn --color=always"

alias yain="yay -S"
alias yacln="yay -Sc"
alias yastat="yay -Ps"
alias yaser="yay -Sc"

alias xq="xbps-query"
alias xql="xbps-query -l"
alias xi="doas xbps-install -S"
alias xr="doas xbps-remove"
alias xrc="doas xbps-remove -RcOo"
alias xrr="doas xbps-remove -ROo"
alias xu="doas xbps-install -Su"

alias aptup="doas apt-get update"
alias aptug="doas apt-get upgrade"
alias aptin="doas apt-get install"
alias aptrm="doas apt-get remove"
alias aptautorm="doas apt-get autoremove"
alias dpkin="doas dpkg -i"
