alias pacin="doas pacman -S --color=always"
alias paccln="doas pacman -Sc --color=always"
alias pacsync="doas pacman -Sy --color=always"
alias pacsrch="doas pacman -Ss --color=always"
alias pacup="doas pacman -Syu --color=always"
alias pacrem="doas pacman -Rsn --color=always"
alias pacq="pacman -Q"
alias pacqi="pacman -Qi"
alias pacql="pacman -Ql"

alias yain="yay -S"
alias yacln="yay -Sc"
alias yastat="yay -Ps"
alias yaser="yay -Sc"
alias yau="yay -Syu"
alias yas="yay -Ss"

alias xq="xbps-query"
alias xql="xbps-query -l"
alias xqs="xbps-query -Rs"
alias xqi="xbps-query -S"
alias xi="doas xbps-install -S"
alias xr="doas xbps-remove"
alias xrc="doas xbps-remove -RcOo"
alias xrr="doas xbps-remove -ROo"
alias xu="doas xbps-install -Su"

alias aptup="doas apt-get update"
alias aptug="doas apt-get upgrade"
alias aptin="doas apt-get install"
alias aptrm="doas apt-get remove"
alias aptautorm="doas apt-get autoremove"
alias aptsrch="apt-cache search"
alias aptshow="apt-cache show"
alias dpkin="doas dpkg -i"
