local vg = vim.g
local vo = vim.opt

vg.loaded_netrw = 1
vg.loaded_netrwPlugin = 1
vo.tabstop = 4
vo.shiftwidth = 4
vo.expandtab = true
vo.smartindent = true
vo.breakindent = true
vo.wrap = false
vo.linebreak = true
vo.number = true
vo.relativenumber = true
vo.cursorline = true
vo.signcolumn = "yes"
vo.scrolloff = 8
vo.sidescrolloff = 8
vo.splitbelow = true
vo.splitright = true
vo.ignorecase = true
vo.smartcase = true
vo.inccommand = "split"
vo.undofile = true
vo.updatetime = 200
vo.timeoutlen = 400
vo.visualbell = true
vg.autoformat = true
